name: Deploy Live Infrastructure

on:
  push:
    branches: [main]
    tags: ["v*"]
    paths:
      - "infrastructure-live/**"
      - "terraform-modules/**"
      - ".github/workflows/deploy-live.yml"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (dev, stage, prod)"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

jobs:
  plan:
    name: "Plan: ${{ inputs.environment || (startsWith(github.ref, 'refs/tags/') && 'prod') || 'dev' }}"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure-live
    env:
      TF_ENV: ${{ inputs.environment || (startsWith(github.ref, 'refs/tags/') && 'prod') || 'dev' }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Select Workspace
        run: terraform workspace select ${{ env.TF_ENV }} || terraform workspace new ${{ env.TF_ENV }}

      - name: Terraform Plan
        run: terraform plan -var-file="${{ env.TF_ENV }}.tfvars" -out=tfplan

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ env.TF_ENV }}
          path: infrastructure-live/tfplan

  apply:
    needs: plan
    name: "Apply: ${{ inputs.environment || (startsWith(github.ref, 'refs/tags/') && 'prod') || 'dev' }}"
    runs-on: ubuntu-latest
    # THIS IS THE GATE: The environment protection rule will PAUSE this specific job
    environment:
      name: ${{ inputs.environment || (startsWith(github.ref, 'refs/tags/') && 'prod') || 'dev' }}
    defaults:
      run:
        working-directory: ./infrastructure-live
    env:
      TF_ENV: ${{ inputs.environment || (startsWith(github.ref, 'refs/tags/') && 'prod') || 'dev' }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Select Workspace
        run: terraform workspace select ${{ env.TF_ENV }} || terraform workspace new ${{ env.TF_ENV }}

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan-${{ env.TF_ENV }}
          path: infrastructure-live

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
